### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by juaxix** [connorlanigan/unrealengine-docker#1]
Hello Connor, I'm trying to run your docker but it got stuck in the git part, this is the log:

```
$ docker run connorlanigan/unrealengine-docker
Cloning into 'UnrealEngine'...
fatal: unable to access 'https://github.com/EpicGames/UnrealEngine.git/': Could not resolve host: github.com
```
Maybe you need to make a network configuration to be able to connect to internet?

**Comment by connorlanigan** [comment]
Hey Juan, thanks for reporting this. Unfortunately, I was unable to reproduce this result. When running the command on a freshly installed Ubuntu machine in a data center in Nuremberg, the process looks like this:
```
root@ubuntu-2gb-nbg1-dc3-1 ~ # docker run -ti connorlanigan/unrealengine-docker
Cloning into 'UnrealEngine'...
Username for 'https://github.com': connorlanigan
Password for 'https://connorlanigan@github.com':
remote: Counting objects: 82973, done.
remote: Compressing objects: 100% (63634/63634), done.
remote: Total 82973 (delta 18474), reused 62998 (delta 17303), pack-reused 0
Receiving objects: 100% (82973/82973), 166.99 MiB | 16.75 MiB/s, done.
Resolving deltas: 100% (18474/18474), done.
Checking connectivity... done.
Checking out files: 100% (89624/89624), done.
Get:1 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
```

A specific network configuration should not be necessary for this script. 
Usually and by default, a docker container can freely access the internet (as long as the host machine has internet access). My guess is that the machine itself that you're running this command on has trouble with its connection (instead of problems with docker).

If the issue still persists, it might be easier to help if you can give the following details:
 * what kind of machine are you running this on? (server or local machine, operating system)
 * do you have any firewall setup?

**Comment by juaxix** [comment]
Looks like it wont work in my local machine but it works in the docker cloud...I'm running it in my computer a normal PC with Ubuntu 16.04, no firewall...
